### PR TITLE
Switch to BeatSaberDir

### PR DESCRIPTION
**Pull request by JonnyVR1**

### CODE REVIEW

**Comment by Kylon99** [comment]
What is this push request for?

**Comment by JonnyVR1** [comment]
Self-explanatory really...  The rest of Beat Saber mods use BeatSaberDir rather than GameDir so bringing this up to the rest of the projects.

**Comment by Kylon99** [comment]
This PR is unsuitable due to the gitignore changes.  Also I am not part of the other Beat Saber mod development and I'm not willing to ask my contributors to change at this moment.  I will consider it for the future though if we ever adopt BSMT.

**Comment by JonnyVR1** [comment]
> This PR is unsuitable due to the gitignore changes

You're joking right? Seriously... adding things used by other IDE's other than Visual Studio is a blocking issue? Are you insane or just dumb?

**Comment by Kylon99** [comment]
Blocking JonnyVR1 due to lack of communication and childish name calling.

**Pull request closed without merging**
